# left_format = ""
#
# format = """$character"""
# right_format = """$all"""


[hostname]
ssh_only = false
disabled = false
format = '[ğŸ–¥ï¸$hostname](dimmed) '
ssh_symbol = 'ğŸŒ'

[dotnet]
disabled = true

[direnv]
disabled = true

[deno]
disabled = true

[nodejs]
disabled = true

[python]
disabled = true

[ruby]
disabled = true

[package]
disabled = true

[[battery.display]]
threshold = 50

[custom.urgent_tasks]
command = '/home/jumski/.dotfiles/todoist-helper/bin/urgent-status.sh'
when = 'test $? -eq 1'
style = 'bold red'
format = '[$output](style) '
