- link:
    ~/.opencode/commands: claude/commands
    ~/.opencode/opencode.jsonc: opencode/opencode.jsonc
    ~/.opencode/plugin/superpowers.js: ~/.config/opencode/superpowers/.opencode/plugin/superpowers.js
