- link:
    ~/.Xmodmap: keyboard/Xmodmap.symlink
    ~/.agignore: system/agignore.symlink
    ~/.psqlrc: postgres/psqlrc.symlink
    ~/.tool-versions: tool-versions.symlink
    ~/.ssh/config:
      path: /home/jumski/SynologyDrive/Areas/Dev/ssh-config
      ignore-missing: true
      create: true
    ~/.config/starship.toml: starship/starship.toml
